#!/system/bin/sh


echo down | ./hid-gadget-test /dev/hidg1 keyboard
echo down | ./hid-gadget-test /dev/hidg1 keyboard
echo left | ./hid-gadget-test /dev/hidg1 keyboard
echo enter | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.2
echo left-ctrl n | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.5
echo left-ctrl l | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.6

echo g i t h u b | ./hid-gadget-test /dev/hidg1 keyboard
echo period | ./hid-gadget-test /dev/hidg1 keyboard
echo c o m | ./hid-gadget-test /dev/hidg1 keyboard
echo slash | ./hid-gadget-test /dev/hidg1 keyboard
echo s p a d e s | ./hid-gadget-test /dev/hidg1 keyboard
echo minus | ./hid-gadget-test /dev/hidg1 keyboard
echo a c e | ./hid-gadget-test /dev/hidg1 keyboard

sleep 0.3
echo enter | ./hid-gadget-test /dev/hidg1 keyboard
