#!/system/bin/sh

echo left-meta r | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.3
echo i e x p l o | ./hid-gadget-test /dev/hidg1 keyboard
echo r e | ./hid-gadget-test /dev/hidg1 keyboard
echo space | ./hid-gadget-test /dev/hidg1 keyboard
echo minus | ./hid-gadget-test /dev/hidg1 keyboard
echo k | ./hid-gadget-test /dev/hidg1 keyboard
echo space | ./hid-gadget-test /dev/hidg1 keyboard

echo g i t h u b | ./hid-gadget-test /dev/hidg1 keyboard
echo period | ./hid-gadget-test /dev/hidg1 keyboard
echo c o m | ./hid-gadget-test /dev/hidg1 keyboard
echo slash | ./hid-gadget-test /dev/hidg1 keyboard
echo s p a d e s | ./hid-gadget-test /dev/hidg1 keyboard
echo left-shift minus | ./hid-gadget-test /dev/hidg1 keyboard
echo a c e | ./hid-gadget-test /dev/hidg1 keyboard


sleep 0.3
echo enter | ./hid-gadget-test /dev/hidg1 keyboard
